name: "Savant Home Assistant Proxy"
version: "1.1.3"
slug: "savant_home_assistant_proxy"
description: "An add-on to run a two-way connection between a Savant System and Home Assistant."
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: "auto"
ports:
  8080/tcp: 8080
host_network: true
startup: services
homeassistant_api: true